export const QuizData = {
  albums: [
    {
      id: '5MIGplDUloZZdW8izdHzJe',
      genres: ['afrobeat'],
      imageUrl: 'https://i.scdn.co/image/19e1d60f10e5354055177a7a0e7ff28e10af2666'
    },
    {
      id: '4F8xZbW4Gwu3xH58vmtbN0',
      genres: ['black-metal'],
      imageUrl: 'https://i.scdn.co/image/17edc29f6c1f88c3ec904cc76b0dcff56e400dd0'
    },
    {
      id: '0uQnXXbHhO6BQ1vFcwMwT8',
      genres: ['country'],
      imageUrl: 'https://i.scdn.co/image/6257e1510a07d43119d7fae8ded7679c82a433db'
    },
    {
      id: '7ds4kb9n2nn5GgMSigTQq0',
      genres: ['dubstep'],
      imageUrl: 'https://i.scdn.co/image/5fda4755b340032763d17fb43b44aa815a77caef'
    },
    {
      id: '0WLWAE1tb53NWqQ9fLsOmS',
      genres: ['industrial'],
      imageUrl: 'https://i.scdn.co/image/e58184d0fd84a7142e05f3cf2bf02604ee2002c8'
    },
    {
      id: '5fmIolILp5NAtNYiRPjhzA',
      genres: ['jazz'],
      imageUrl: 'https://i.scdn.co/image/777219e85b97000df64413920f12c015b6b12d37'
    },
    {
      id: '0tiV72iGvJH8eHfDCTuI85',
      genres: ['opera'],
      imageUrl: 'https://i.scdn.co/image/09e0c7a89be67483846123794fc75d3fe6034bfa'
    },
    {
      id: '6daHGcQra17Pvgnp5gEzJm',
      genres: ['ambient'],
      imageUrl: 'https://i.scdn.co/image/b5dca98dcdbcdb675529aa0386ef97ab93f129fe'
    },
    {
      id: '7czYIT2adKSBYFfmAbyAVm',
      genres: ['death-metal'],
      imageUrl: 'https://i.scdn.co/image/10f29a4539913f34044e26798b3030d465c28171'
    },
    {
      id: '6zRPOKKIiUEQPGYnLoavVj',
      genres: ['electronic'],
      imageUrl: 'https://i.scdn.co/image/4822543244acb00561bb43dee4326889d555f058'
    }
    
  ],
  genres: [
     "acoustic",
     "afrobeat",
     "alt-rock",
     "alternative",
     "ambient",
     "anime",
     "black-metal",
     "bluegrass",
     "blues",
     "bossanova",
     "brazil",
     "breakbeat",
     "british",
     "cantopop",
     "chicago-house",
     "children",
     "chill",
     "classical",
     "club",
     "comedy",
     "country",
     "dance",
     "dancehall",
     "death-metal",
     "deep-house",
     "detroit-techno",
     "disco",
     "disney",
     "drum-and-bass",
     "dub",
     "dubstep",
     "edm",
     "electro",
     "electronic",
     "emo",
     "folk",
     "forro",
     "french",
     "funk",
     "garage",
     "german",
     "gospel",
     "goth",
     "grindcore",
     "groove",
     "grunge",
     "guitar",
     "happy",
     "hard-rock",
     "hardcore",
     "hardstyle",
     "heavy-metal",
     "hip-hop",
     "holidays",
     "honky-tonk",
     "house",
     "idm",
     "indian",
     "indie",
     "indie-pop",
     "industrial",
     "iranian",
     "j-dance",
     "j-idol",
     "j-pop",
     "j-rock",
     "jazz",
     "k-pop",
     "kids",
     "latin",
     "latino",
     "malay",
     "mandopop",
     "metal",
     "metal-misc",
     "metalcore",
     "minimal-techno",
     "movies",
     "mpb",
     "new-age",
     "new-release",
     "opera",
     "pagode",
     "party",
     "philippines-opm",
     "piano",
     "pop",
     "pop-film",
     "post-dubstep",
     "power-pop",
     "progressive-house",
     "psych-rock",
     "punk",
     "punk-rock",
     "r-n-b",
     "rainy-day",
     "reggae",
     "reggaeton",
     "road-trip",
     "rock",
     "rock-n-roll",
     "rockabilly",
     "romance",
     "sad",
     "salsa",
     "samba",
     "sertanejo",
     "show-tunes",
     "singer-songwriter",
     "ska",
     "sleep",
     "songwriter",
     "soul",
     "soundtracks",
     "spanish",
     "study",
     "summer",
     "swedish",
     "synth-pop",
     "tango",
     "techno",
     "trance",
     "trip-hop",
     "turkish",
     "work-out",
     "world-music"
  ]
}